"use client";

import { useEffect, useMemo, useState } from "react";
import { Boxes, CreditCard, FolderTree, MessageCircle, Plus, Send, Settings2, Trash2, UsersRound } from "lucide-react";
import type { DemoSnapshot, Order, OrderStatus } from "@/lib/types";
import { formatMAD, statusLabels } from "@/lib/types";
import { firebaseServices } from "@/lib/firebase/client";
import { getBrowserDemoOrders, getBrowserSupportTickets, saveBrowserSupportTickets, updateBrowserDemoOrder, type BrowserDemoOrder, type BrowserSupportTicket } from "@/lib/demo-browser";
import { AdminSessionControls } from "@/components/admin-session-controls";

const statusOptions: OrderStatus[] = ["new", "processing", "waiting", "completed", "rejected"];
const orderTone = (status: OrderStatus) => ({ new: "blue", processing: "amber", waiting: "violet", completed: "green", rejected: "red" }[status]);
const fieldLabels: Record<string, string> = { email: "البريد الإلكتروني", imei: "IMEI", model: "موديل الجهاز", serial: "Serial Number", username: "اسم المستخدم", plan: "الباقة", duration: "مدة الكراء", game: "اللعبة", playerId: "Player ID" };
type Tab = "overview" | "orders" | "products" | "categories" | "customers" | "support" | "settings";
type DisplayOrder = Order & { browserOrder?: BrowserDemoOrder };

export function AdminConsole({ initial }: { initial: DemoSnapshot }) {
  const [data, setData] = useState(initial);
  const [tab, setTab] = useState<Tab>("overview");
  const [openFolder, setOpenFolder] = useState<string | null>(null);
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const [typedName, setTypedName] = useState("");
  const firebase = firebaseServices();
  const [notice, setNotice] = useState(firebase ? "Firebase متصل: تحديثات الطلبات تُحفظ في قاعدة البيانات الحقيقية." : "وضع تجريبي: التغييرات هنا محلية وتُحفظ في المتصفح فقط.");
  const [tickets, setTickets] = useState<BrowserSupportTicket[]>([]);
  const [browserOrders, setBrowserOrders] = useState<BrowserDemoOrder[]>([]);
  const [deliveryDrafts, setDeliveryDrafts] = useState<Record<string, string>>({});
  const [deliveryNotes, setDeliveryNotes] = useState<Record<string, string>>({});
  const [selectedCustomerId, setSelectedCustomerId] = useState<string | null>(null);

  useEffect(() => {
    if (firebase) return;
    const refresh = () => { setTickets(getBrowserSupportTickets()); setBrowserOrders(getBrowserDemoOrders()); };
    refresh(); window.addEventListener("chrigsm:demo-support", refresh); window.addEventListener("chrigsm:demo-order", refresh);
    return () => { window.removeEventListener("chrigsm:demo-support", refresh); window.removeEventListener("chrigsm:demo-order", refresh); };
  }, [firebase]);

  const allOrders = useMemo<DisplayOrder[]>(() => firebase ? data.orders : [
    ...browserOrders.map((order) => ({ id: order.id, customerId: order.customerId, serviceId: order.serviceId, status: order.status, totalMad: order.totalMad, createdAt: order.createdAt, updatedAt: order.updatedAt, deliveryCode: order.deliveryCode, deliveryNote: order.deliveryNote, formData: order.answers, statusHistory: order.statusHistory, notification: order.notification, browserOrder: order })),
    ...data.orders,
  ], [browserOrders, data.orders, firebase]);
  const totalWallet = useMemo(() => data.customers.reduce((sum, item) => sum + item.walletMad, 0), [data.customers]);
  const processing = allOrders.filter((item) => item.status === "processing").length;
  const activeCategory = data.categories.find((item) => item.id === openFolder);
  const visibleOrders = selectedCustomerId ? allOrders.filter((order) => order.customerId === selectedCustomerId) : allOrders;

  async function patchFirebaseOrder(orderId: string, payload: { status?: OrderStatus; deliveryCode?: string; deliveryNote?: string }) {
    const user = firebase?.auth.currentUser;
    if (!firebase || !user) return false;
    const response = await fetch(`/api/orders/${orderId}`, { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${await user.getIdToken()}` }, body: JSON.stringify(payload) });
    const result = await response.json() as { error?: string };
    if (!response.ok) throw new Error(result.error || "تعذر حفظ تحديث الطلب في Firebase.");
    return true;
  }
  async function updateOrder(orderId: string, status: OrderStatus) {
    const target = allOrders.find((order) => order.id === orderId);
    if (!target) return;
    const now = new Date().toISOString();
    const note = status === "processing" ? "بدأ فريق ChriGsm معالجة الطلب. بيانات العميل أصبحت مقفلة." : `غيّر فريق ChriGsm الحالة إلى «${statusLabels[status]}».`;
    try {
      if (firebase) await patchFirebaseOrder(orderId, { status });
      if (target.browserOrder && !firebase) updateBrowserDemoOrder(orderId, (order) => ({ ...order, status, updatedAt: now, statusHistory: [...order.statusHistory, { status, at: now, note }] }));
      else setData((previous) => ({ ...previous, orders: previous.orders.map((order) => order.id === orderId ? { ...order, status, updatedAt: now, statusHistory: [...(order.statusHistory || []), { status, at: now, note }] } : order) }));
      setNotice(`تم تحديث الطلب ${orderId} إلى «${statusLabels[status]}».`);
    } catch (reason) { setNotice(reason instanceof Error ? reason.message : "تعذر تحديث الطلب."); }
  }
  async function sendDelivery(orderId: string) {
    const target = allOrders.find((order) => order.id === orderId);
    const code = deliveryDrafts[orderId]?.trim();
    const deliveryNote = deliveryNotes[orderId]?.trim();
    if (!target || !code) { setNotice("أدخل كود التفعيل أو تفاصيل التسليم أولًا."); return; }
    const now = new Date().toISOString();
    const notification = { title: "تم إنجاز طلبك بنجاح", body: `تم تسليم ${data.services.find((service) => service.id === target.serviceId)?.title || "الخدمة"}. راجع كود التسليم في تفاصيل الطلب.`, createdAt: now, read: false };
    const history = { status: "completed" as const, at: now, note: "تم إرسال كود أو تفاصيل التسليم إلى حساب العميل." };
    try {
      if (firebase) await patchFirebaseOrder(orderId, { deliveryCode: code, deliveryNote });
      if (target.browserOrder && !firebase) updateBrowserDemoOrder(orderId, (order) => ({ ...order, status: "completed", deliveryCode: code, deliveryNote, updatedAt: now, statusHistory: [...order.statusHistory, history], notification }));
      else setData((previous) => ({ ...previous, orders: previous.orders.map((order) => order.id === orderId ? { ...order, status: "completed", deliveryCode: code, deliveryNote, notification, updatedAt: now, statusHistory: [...(order.statusHistory || []), history] } : order) }));
      setNotice(`تم التسليم للطلب ${orderId}. وصل إشعار داخل الحساب؛ WhatsApp ينتظر إعداد التكامل الحقيقي.`);
    } catch (reason) { setNotice(reason instanceof Error ? reason.message : "تعذر تسليم الطلب."); }
  }
  function answerTicket(ticketId: string) { const next = tickets.map((ticket) => ticket.id === ticketId ? { ...ticket, status: "answered" as const } : ticket); setTickets(next); saveBrowserSupportTickets(next); setNotice(`تم وضع رسالة الدعم ${ticketId} كـ«تم الرد».`); }
  function adjustWallet(customerId: string, delta: number) { setData((previous) => ({ ...previous, customers: previous.customers.map((customer) => customer.id === customerId ? { ...customer, walletMad: Math.max(0, customer.walletMad + delta) } : customer) })); setNotice("تم تعديل الرصيد التجريبي. النسخة الحقيقية ستنفذها بسجل تدقيق خادمي."); }
  function addDemoService(categoryId: string) { const category = data.categories.find((item) => item.id === categoryId); if (!category) return; const id = `svc-demo-${Date.now()}`; setData((previous) => ({ ...previous, services: [...previous.services, { id, slug: id, title: "خدمة تجريبية جديدة", categoryId, description: "خدمة أضيفت من لوحة CMC التجريبية ويمكن تعديلها عند ربط Firebase.", priceMad: 0, delivery: "تحتاج تسعير", isActive: false, fields: [] }] })); setNotice(`أضيفت خدمة تجريبية إلى مجلد «${category.name}».`); }
  function deleteCategory() { const category = data.categories.find((item) => item.id === deleteId); if (!category || typedName !== category.name) return; setData((previous) => ({ ...previous, categories: previous.categories.filter((item) => item.id !== category.id), services: previous.services.filter((service) => service.categoryId !== category.id) })); setDeleteId(null); setTypedName(""); setNotice(`حُذف التصنيف «${category.name}» مع جميع خدماته التجريبية التابعة.`); }
  function addCategory() { const id = `cat-demo-${Date.now()}`; setData((previous) => ({ ...previous, categories: [...previous.categories, { id, name: "تصنيف تجريبي", icon: "Folder", color: "#1479FF", description: "تصنيف أضيف محليًا", order: previous.categories.length + 1, isActive: true }] })); setNotice("أضيف تصنيف تجريبي جديد. عدل الاسم والأيقونة بعد اتصال Firebase."); }

  return <div className="admin-console"><aside className="cmc-sidebar"><div className="cmc-title">ChriGsm <b>CMC</b></div><nav>{([ ["overview","نظرة عامة"], ["orders","الطلبات"], ["products","المنتجات"], ["categories","التصنيفات"], ["customers","العملاء"], ["support","الدعم"], ["settings","الإعدادات"] ] as [Tab,string][]).map(([id,label]) => <button className={tab === id ? "active" : ""} onClick={() => setTab(id)} key={id}>{label}</button>)}</nav><div className="demo-mode">{firebase ? <>Firebase متصل<br/><span>الطلبات تُحفظ في Firestore</span></> : <>وضع تجريبي<br/><span>الطلبات تُحفظ على هذا المتصفح</span></>}</div></aside><section className="cmc-content"><header className="cmc-heading"><div><p className="eyebrow">إدارة العمليات</p><h1>{({ overview:"نظرة عامة CMC", orders:"إدارة الطلبات", products:"مجلدات المنتجات", categories:"إدارة التصنيفات", customers:"العملاء والمحافظ", support:"رسائل الدعم", settings:"إعدادات المتجر" } as Record<Tab,string>)[tab]}</h1></div><span className="live-pill"><span/> {firebase ? "Firebase متصل" : "تجربة محلية"}</span></header><p className="admin-notice">{notice}</p>
    {tab === "overview" && <><div className="metric-grid"><Metric icon={<UsersRound/>} label="عملاء نشطون" value={String(data.customers.length)} note="بيانات تجريبية"/><Metric icon={<Boxes/>} label="طلبات جديدة" value={String(allOrders.filter((item) => item.status === "new").length)} note="تصل من المتجر"/><Metric icon={<FolderTree/>} label="قيد المعالجة" value={String(processing)} note="بيانات مقفلة للعميل"/><Metric icon={<CreditCard/>} label="إجمالي الأرصدة" value={formatMAD(totalWallet)} note="محافظ العملاء"/></div><section className="cmc-card"><h2>آخر الطلبات</h2><OrderGrid orders={allOrders} data={data} onStatus={updateOrder} deliveryDrafts={deliveryDrafts} deliveryNotes={deliveryNotes} onDeliveryDraft={setDeliveryDrafts} onDeliveryNote={setDeliveryNotes} onSendDelivery={sendDelivery}/></section></>}
    {tab === "orders" && <section className="cmc-card"><div className="section-title"><div><p className="eyebrow">بيانات وتسليم واضح</p><h2>طلبات الخدمات</h2></div>{selectedCustomerId ? <button className="filter-button" onClick={() => setSelectedCustomerId(null)}>كل العملاء</button> : <span className="muted-text">يصل إشعار داخل الحساب عند الإكمال</span>}</div><OrderGrid orders={visibleOrders} data={data} onStatus={updateOrder} deliveryDrafts={deliveryDrafts} deliveryNotes={deliveryNotes} onDeliveryDraft={setDeliveryDrafts} onDeliveryNote={setDeliveryNotes} onSendDelivery={sendDelivery}/></section>}
    {tab === "products" && <section className="cmc-card"><div className="section-title"><div><p className="eyebrow">عرض فقط للتصنيفات</p><h2>{activeCategory ? activeCategory.name : "مجلدات المنتجات"}</h2></div>{activeCategory && <button className="filter-button" onClick={() => setOpenFolder(null)}>رجوع للمجلدات</button>}</div>{!activeCategory ? <div className="folder-grid">{data.categories.map((category) => <article className="folder-card" key={category.id} style={{"--folder-color":category.color} as React.CSSProperties}><button className="folder-open" onClick={() => setOpenFolder(category.id)}><span className="folder-icon">{category.icon.slice(0,1)}</span><span><b>{category.name}</b><small>{data.services.filter((item) => item.categoryId === category.id).length} خدمات</small></span></button></article>)}</div> : <div className="product-list">{data.services.filter((item) => item.categoryId === activeCategory.id).map((service) => <article className="product-row" key={service.id}><span className="service-glyph">{service.title.slice(0,2)}</span><div><h3>{service.title}</h3><p>{service.description}</p></div><strong>{formatMAD(service.priceMad)}</strong><button className="filter-button">تعديل</button></article>)}<button className="primary-button" onClick={() => addDemoService(activeCategory.id)}><Plus size={16}/> إضافة منتج تجريبي</button></div>}</section>}
    {tab === "categories" && <section className="cmc-card"><div className="section-title"><div><p className="eyebrow">إضافة وتعديل وحذف</p><h2>التصنيفات والأيقونات</h2></div><button className="primary-button small" onClick={addCategory}><Plus size={15}/> إضافة تصنيف</button></div><div className="category-admin-list">{data.categories.map((category) => <article key={category.id} className="category-admin-row"><span className="folder-icon" style={{"--folder-color":category.color} as React.CSSProperties}>{category.icon.slice(0,1)}</span><div><h3>{category.name}</h3><p>{category.description} · أيقونة: رابط أو رفع عند Firebase</p></div><span className="muted-text">{data.services.filter((item) => item.categoryId === category.id).length} خدمات</span><button className="danger-button" onClick={() => setDeleteId(category.id)}><Trash2 size={15}/> حذف</button></article>)}</div></section>}
    {tab === "customers" && <section className="cmc-card"><div className="section-title"><div><p className="eyebrow">المحافظ والتواصل</p><h2>العملاء</h2></div><span className="muted-text">التعديلات خادمية عند Firebase</span></div><div className="customer-grid">{data.customers.map((customer) => <article className="customer-card large" key={customer.id}><span className="avatar">{customer.fullName.slice(0,1)}</span><div><h3>{customer.fullName}</h3><p>{customer.phone}</p><strong>رصيد {formatMAD(customer.walletMad)} · {allOrders.filter((order) => order.customerId === customer.id).length} طلبات</strong></div><div className="wallet-actions"><button onClick={() => adjustWallet(customer.id, 50)}>+50</button><button onClick={() => adjustWallet(customer.id, -50)}>-50</button><button onClick={() => { setSelectedCustomerId(customer.id); setTab("orders"); }}>طلبات</button></div></article>)}</div></section>}
    {tab === "support" && <section className="cmc-card"><div className="section-title"><div><p className="eyebrow">منطقة العميل</p><h2>رسائل الدعم</h2></div><span className="muted-text">{tickets.length} رسائل تجريبية</span></div>{tickets.length ? <div className="admin-ticket-list">{tickets.map((ticket) => <article key={ticket.id}><MessageCircle size={20}/><div><b>{ticket.subject}</b><p>{ticket.message}</p><small>{ticket.id} · {ticket.createdAt.slice(0, 10)}</small></div><div><span className={`status-pill ${ticket.status === "open" ? "amber" : "green"}`}>{ticket.status === "open" ? "مفتوح" : "تم الرد"}</span>{ticket.status === "open" && <button className="filter-button" onClick={() => answerTicket(ticket.id)}><Send size={14}/> تم الرد</button>}</div></article>)}</div> : <div className="empty-state"><MessageCircle size={24}/><h2>لا توجد رسائل دعم</h2><p>ستظهر رسائل العملاء هنا عند إرسالها من حساب التجربة أو بعد ربط Firebase.</p></div>}</section>}
    {tab === "settings" && <section className="cmc-card"><div className="section-title"><div><p className="eyebrow">إعداد محلي قبل الإنتاج</p><h2>إعدادات المتجر والإدارة</h2></div><Settings2 size={22}/></div><AdminSessionControls/><div className="admin-settings-grid"><article><p>اسم المتجر</p><strong>ChriGsm</strong><small>يظهر في الرأس ورسائل الحساب</small></article><article><p>عملة المتجر</p><strong>الدرهم المغربي (د.م.)</strong><small>معتمدة في الأسعار والمحافظ</small></article><article><p>WhatsApp Business</p><strong>مؤجل</strong><small>تحتاج API ورقم العمل قبل أي إرسال فعلي</small></article><article><p>المصادقة</p><strong>Firebase Authentication</strong><small>تُفعل بعد إنشاء مشروع Firebase</small></article></div><section className="whatsapp-placeholder"><MessageCircle size={21}/><div><p className="eyebrow">تكامل مؤجل وآمن</p><h3>إشعار WhatsApp عند إتمام الطلب</h3><p>لن تُرسل النسخة التجريبية أي رسالة. عند الجاهزية، سيُنفَّذ الإرسال من دالة خادمية بعد تسليم الطلب فقط، باستخدام رقم WhatsApp Business معتمد وقالب Meta مصادق عليه.</p><div className="whatsapp-requirements"><span>رقم عمل موثّق</span><span>Meta Business API</span><span>قالب رسالة معتمد</span><span>مفاتيح خادمية فقط</span></div></div></section></section>}
  </section>{deleteId && <div className="dialog-backdrop"><div className="confirm-dialog"><p className="eyebrow">حذف متسلسل</p><h2>حذف التصنيف وخدماته؟</h2><p>سيُحذف التصنيف «{data.categories.find((item) => item.id === deleteId)?.name}» وجميع منتجاته التابعة في وضع التجربة. اكتب اسم التصنيف للتأكيد.</p><input autoFocus value={typedName} onChange={(event) => setTypedName(event.target.value)} placeholder="اسم التصنيف"/><div><button className="filter-button" onClick={() => { setDeleteId(null); setTypedName(""); }}>إلغاء</button><button className="danger-button" disabled={typedName !== data.categories.find((item) => item.id === deleteId)?.name} onClick={deleteCategory}>تأكيد الحذف</button></div></div></div>}</div>;
}

function Metric({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string;note:string}){return <article className="metric-card"><span>{icon}</span><p>{label}</p><strong>{value}</strong><small>{note}</small></article>}
function OrderGrid({orders,data,onStatus,deliveryDrafts,deliveryNotes,onDeliveryDraft,onDeliveryNote,onSendDelivery}:{orders:DisplayOrder[];data:DemoSnapshot;onStatus:(id:string,status:OrderStatus)=>void;deliveryDrafts:Record<string,string>;deliveryNotes:Record<string,string>;onDeliveryDraft:React.Dispatch<React.SetStateAction<Record<string,string>>>;onDeliveryNote:React.Dispatch<React.SetStateAction<Record<string,string>>>;onSendDelivery:(id:string)=>void}){return <div className="cmc-order-grid">{orders.map((order)=>{const customer=data.customers.find((item)=>item.id===order.customerId);const service=data.services.find((item)=>item.id===order.serviceId);const history=order.statusHistory?.length ? order.statusHistory : [{status:order.status,at:order.updatedAt,note:`الحالة الحالية: ${statusLabels[order.status]}`}];return <article className="cmc-order-card detailed-cmc-order" key={order.id}><div className="order-card-top"><span className={`status-pill ${orderTone(order.status)}`}>{statusLabels[order.status]}</span><span>{order.id}</span></div><h3>{service?.title || order.browserOrder?.serviceTitle}</h3><p>{customer?.fullName || order.browserOrder?.customerName} · {customer?.phone || order.browserOrder?.customerPhone}</p><strong>{formatMAD(order.totalMad)}</strong><details className="cmc-order-details"><summary>البيانات المرسلة وسجل الطلب</summary><div><b>بيانات العميل</b><p>{order.browserOrder?.customerEmail || customer?.email}</p></div><div><b>الحقول المرسلة</b>{Object.entries(order.formData).map(([key,value])=><p key={key}><span>{fieldLabels[key] || key}</span>{value}</p>)}</div><div><b>سجل الحالة</b>{history.map((event,index)=><p key={`${event.at}-${index}`}><span className={`status-pill ${orderTone(event.status)}`}>{statusLabels[event.status]}</span>{event.note}</p>)}</div></details><select value={order.status} onChange={(event)=>onStatus(order.id,event.target.value as OrderStatus)}>{statusOptions.map((status)=><option key={status} value={status}>{statusLabels[status]}</option>)}</select>{order.status !== "completed" && <div className="delivery-box"><input value={deliveryDrafts[order.id] || ""} onChange={(event)=>onDeliveryDraft((previous)=>({...previous,[order.id]:event.target.value}))} placeholder="كود التفعيل أو تفاصيل التسليم"/><textarea value={deliveryNotes[order.id] || ""} onChange={(event)=>onDeliveryNote((previous)=>({...previous,[order.id]:event.target.value}))} placeholder="ملاحظة تظهر للعميل (اختياري)"/><button type="button" onClick={()=>onSendDelivery(order.id)}>تسليم وإشعار العميل</button></div>}{order.deliveryCode && <code>{order.deliveryCode}</code>}</article>})}</div>}
